services:
  - type: web
    name: nestjs-backend
    env: node
    buildCommand: npm install -g @nestjs/cli && npm install && nest build
    startCommand: node dist/main
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '10000'
